[[redirects]]
  from = "https://golden-chimera-76d804.netlify.app/*"
  to = "hhttps://golden-chimera-76d804.netlify.app/:splat"
  status = 301
  force = true
  
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200