[[redirects]]
  from = "/auth/*"
  to = "http://3.215.131.222:5000/auth/:splat"
  status = 200
  force = true

  [[redirects]]
  from = "/api/summoners/*"
  to = "http://3.215.131.222:5000/api/summoners/:splat"
  status = 200
  force = true

  [[redirects]]
  from = "/post/*"
  to = "http://3.215.131.222:5000/post/:splat"
  status = 200
  force = true
  
  [[redirects]]
  from = "/api/*"
  to = "http://3.215.131.222:5000/api/:splat"
  status = 200
  force = true

 [[redirects]]
  from = "/socket.io/*"
  to = "http://3.215.131.222:5000/socket.io/:splat"
  status = 200
  force = true
  
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200