[[redirects]]
  from = "https://golden-chimera-76d804.netlify.app/auth"
  to = "https://golden-chimera-76d804.netlify.app/auth"
  status = 301
  force = true
  
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200